### ISSUE TITLE
Mining: EditTag

### ISSUE THREAD

**Issue by ArthurBeaulieu** [Squadella/ManaZeak#103]
- Only available at a given rank (TAGE or TAGS)
- Two stages : 
    - Submit (perm `TAGS`) 
    - Save (perm `TAGE`)
- Same transaction type
- Bubble
- Submit tag one by one in db (table TagPending ?)
- In AdminView, TagReview tab to create (w/ voting system for individual tag changes, plus listen button, plus view current track tags)

**Comment by Squadella** [comment]
Done in backend, to be implemented in front.
