### ISSUE TITLE
Selection doesn't update with UI

### ISSUE THREAD

**Issue by Syncrossus** [Squadella/ManaZeak#128]
Context : when selecting multiple tracks and clicking "next track" button
Expected behavior : Either the selection doesn't change or the next played song is highlighted and the selection is discarded
Actual behavior : the selected songs are not highlighted anymore, the next played song is highlighted but the selection remains the same internally. If, for example, the user adds the highlighted track to a playlist, all of the previously selected songs are added to that playlist.

**Comment by Oxydiz** [comment]
Fixed as of b7effab2158e5bcb23cbe68dd222829e4877ae20
