### ISSUE TITLE
Resize album art on small screens

### ISSUE THREAD

**Issue by Syncrossus** [Squadella/ManaZeak#132]
The album art doesn't necessarily fit in the page on smaller screens. It could ideally be resized to fit within the page where necessary.

Illustration of the issue :
![image](https://user-images.githubusercontent.com/12431317/38547893-92973b6e-3cb0-11e8-9a6a-0e1b1c728809.png)

**Comment by Oxydiz** [comment]
Fixed as of a97c11e43878025bb9be439439648c098b70dad2
