### ISSUE TITLE
Create the folder and the file for logging in mzk script

### ISSUE THREAD

**Issue by Squadella** [Squadella/ManaZeak#145]
Create a folder log in the root of the project with a file named debug.log inside. Also check if the file exists at each launch and create it if it's not the case.

**Comment by Oxydiz** [comment]
In the bugHunt branch, this was already done upon calling init.
The directory structure is now checked when calling the init, dev and prod subscripts.

See d417844d29adcdbf490c7b3871b001fe89189bfb
