### ISSUE TITLE
Switching playlist view scrolls back up to top

### ISSUE THREAD

**Issue by Syncrossus** [Squadella/ManaZeak#20]
**Context :** When switching currently viewed playlist from _playlist A_ to _playlist B_ and back to A
**Expected behavior :** the songs currently displayed on screen should be either the same as before I switched playlists or centered on the song I am currently listening to
**Actual behavior :** playlist A is scrolled back to top and I need to scroll down manually or search with ctrl+F to get back to my place

**Comment by Oxydiz** [comment]
Fixed as of ebe36506d43ca99cb013be373bd5659dd227b763
