### ISSUE TITLE
Counterintuitive button for exiting party mode

### ISSUE THREAD

**Issue by Syncrossus** [Squadella/ManaZeak#26]
The "back" button in party mode shouldn't be the same as the track suggestion button.
I created an alternative graphic that should be copacetic with the UI, you may use it under the [WTFPL licence](http://www.wtfpl.net/about/). I can adjust it if you'd like.
[download back_arrow.zip](https://github.com/Squadella/ManaZeak/files/1604284/back.arrow.zip)

**Comment by ArthurBeaulieu** [comment]
Party button, and especially here the back button is still a work in progress. Some graphics still nedds to be done so the back button is more like a placeholder here than a real button! Thx for the assets, we might look at this in the following days.
