### ISSUE TITLE
Hovering over proposed track VFX ignores TrackInfo boundaries

### ISSUE THREAD

**Issue by Syncrossus** [Squadella/ManaZeak#28]
Context : when hovering over a track proposed in a TrackInfo infobox
Expected behavior : area around track name darkens within the confines of the infobox
Actual behavior : area around track name darkens ignoring the boundaries of the infobox
[Screenshot illustrating the problem](http://puu.sh/yUXnv/31e8d85fa9.png)

**Comment by Oxydiz** [comment]
Fixed as of 11a81d1b7429ef413c6966d8eba4eff7ecea8744
