### ISSUE TITLE
Moodbar thumb displaying when the moodbar isn't present. 

### ISSUE THREAD

**Issue by Squadella** [Squadella/ManaZeak#35]
When the moodbar doesn't exist the thumb still display.
![image](https://user-images.githubusercontent.com/10008695/34915094-c5139e36-f91f-11e7-9c7a-b8837bc22aa5.png)

**Comment by ArthurBeaulieu** [comment]
To be closed I guess ?

**Comment by ArthurBeaulieu** [comment]
Yes, to be closed!
