### ISSUE TITLE
Creating a playlist stall the application

### ISSUE THREAD

**Issue by Squadella** [Squadella/ManaZeak#37]
When creating an empty playlist the application freezes during 30 seconds at least. It must be a reload that maybe isn't needed. 
![image](https://user-images.githubusercontent.com/10008695/34915382-16d68700-f926-11e7-8849-20741a97980d.png)

**Comment by Oxydiz** [comment]
Fixed as of d8410f39aca7967a2d866b512520b810fdebe3df
