### ISSUE TITLE
After deleting a playlist a wrong behavior is observed.

### ISSUE THREAD

**Issue by Squadella** [Squadella/ManaZeak#38]
When deleting an empty playlist between a library and an empty playlist. Like the screen shot below:
![image](https://user-images.githubusercontent.com/10008695/34915596-86d90dcc-f929-11e7-8ba3-3efa740bc5e1.png)

After deleting the user see the content of the library but the empty playlist is selected in the topbar. Also, there is a high usage of CPU that never end. Seems like an infinite loop for me.
![image](https://user-images.githubusercontent.com/10008695/34915542-d8d09d62-f928-11e7-8e45-98cde8617b85.png)

If you click on the playlist "test" the application return to a normal behavior and it stops the inifinite loop.
![image](https://user-images.githubusercontent.com/10008695/34915665-7c6fbad8-f92a-11e7-9cfa-b6f0ff23401a.png)

**Comment by Oxydiz** [comment]
Fixed as of 2be5664a89e026531184c8944e781345c4529408
