### ISSUE TITLE
After clicking on the user drag down options wrong behavior is observed

### ISSUE THREAD

**Issue by Squadella** [Squadella/ManaZeak#39]
When you click in the top bar, the menu isn't dismissed.
When you click in the main view the menu is dismissed, but you have to click twice to make it appears again.
When you change page the menu is dismissed, but you also have to click twice to display it again.

**Comment by Syncrossus** [comment]
> When you click in the main view the menu is dismissed
The only place I can click to dismiss the menu is the bottom bar.

**Comment by Oxydiz** [comment]
Fixed as of 258e02bc49c25b47e1b7b33db97bd6d83d6d6ae3
