### ISSUE TITLE
Phantom playlist

### ISSUE THREAD

**Issue by Syncrossus** [Squadella/ManaZeak#40]
Starting to create a new playlist or library (either by right clicking a song or with the `+` button) but dismissing the dialog box causes what I assume to be a "phantom tab" to appear if another playlist is subsequently created, effectively creating a space between previously created playlists. Phantom tabs cannot be clicked, and disappear upon reloading the page.
Three stacked phantom tabs :
![image](https://user-images.githubusercontent.com/12431317/34916013-f3282434-f930-11e7-8a0e-1d8fdc84c4e7.png)

**Comment by ArthurBeaulieu** [comment]
On which branch where you at this time ? Can not reproduce from de394b2.

**Comment by Syncrossus** [comment]
I am on the in-production version

**Comment by ArthurBeaulieu** [comment]
Sry didn't thought of that. Master (ie production) is ... so late compare to dev :p Update inc by the end of the week, guess we'll close this afterward
