### ISSUE TITLE
Persisting menu when creating playlist

### ISSUE THREAD

**Issue by Syncrossus** [Squadella/ManaZeak#41]
When creating a playlist or library with the `+` button, the menu persists but moves slightly as shown in these screenshots :
![image](https://user-images.githubusercontent.com/12431317/34916110-b17df9da-f932-11e7-9750-0e55d47f0860.png)

**Comment by Oxydiz** [comment]
Fixed as of 258e02bc49c25b47e1b7b33db97bd6d83d6d6ae3
