### ISSUE TITLE
User stats repeat when accessed multiple times

### ISSUE THREAD

**Issue by Syncrossus** [Squadella/ManaZeak#42]
Every time a user accesses their statistics within a session, the number of tracks played and uploaded is appended to the already-existing string of text :
![image](https://user-images.githubusercontent.com/12431317/34916145-57bcad50-f933-11e7-98c1-ca702f87a87f.png)
Obviously, I have listened to 227 tracks and consulted my statistics three times this session, not listened to 227227227 songs.

**Comment by ArthurBeaulieu** [comment]
Resolved in UI, to come in master
