### ISSUE TITLE
Playlist creation bad behavior

### ISSUE THREAD

**Issue by Squadella** [Squadella/ManaZeak#85]
If you spam the button in the modal create library you can create multiple empty playlists. Like this: 
![image](https://user-images.githubusercontent.com/10008695/35776692-86ac8580-09a1-11e8-8b55-af0f6a2bc6f8.png)
Also only one playlist appears after this in the web page:
![image](https://user-images.githubusercontent.com/10008695/35776695-9fff158e-09a1-11e8-8ea4-562d9e39e4d5.png)
After refreshing the UI all the playlists are displayed:
![image](https://user-images.githubusercontent.com/10008695/35776701-b2017b14-09a1-11e8-95a0-41b6bc22d6c3.png)

**Comment by Oxydiz** [comment]
Fixed as of 3feb1fad552e0f6ac21bb15149ccd89128a16215
