### ISSUE TITLE
Syncthing config folder Docker

### ISSUE THREAD

**Issue by avignat** [Squadella/ManaZeak#9]
![capture d ecran 2017-12-03 a 22 19 55](https://user-images.githubusercontent.com/1545450/33530274-77d8f39a-d87d-11e7-8907-01bf29770727.png)

**Comment by ArthurBeaulieu** [comment]
@avignat @Belash Is it closed since ?

**Comment by ArthurBeaulieu** [comment]
Since no response, this is snoozed
